from dash import html
from dash import dash_table, callback, Output, Input
import dash_bootstrap_components as dbc
from constants.styles import TABLE_HEADER_STYLE, TABLE_CELL_STYLE, TABLE_STYLE

# Define Table
table_data = [
    {'JO No.': '24-001-JO-ISOW-SAN', 'Sales Executive': 'Shaica Naoe', 'Date Created': 'Jan 03, 2024', 'Event Name': 'ISOW 2024', 'Venue': 'Megatrade 1-3', 'Event Start Date': 'Jan 06, 2024', 'Event End Date': 'Jan 07, 2024', 'Company Name': 'I Am World Corporation', 'Contact Person': 'Edwin Cano', 'Contact No.': 'N/A', 'Email Address': 'N/A', 'Ingress Date': 'Jan 06, 2024', 'Ingress Time': '09:00 AM', 'Egress Date': 'Jan 06, 2024', 'Egress Time': '07:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-002-JO-HLS-MGD', 'Sales Executive': 'Cecil Derama', 'Date Created': 'Jan 09, 2024', 'Event Name': 'HERBALIFE SPECTACULAR 2024', 'Venue': 'World Trade Center', 'Event Start Date': 'Jan 13, 2024', 'Event End Date': 'Jan 14, 2024', 'Company Name': 'Quiplist Events Production, Inc.', 'Contact Person': 'Kate Gatchalian', 'Contact No.': '0965-877-1856', 'Email Address': 'prod.quiplist@gmail.com', 'Ingress Date': 'Jan 12, 2024', 'Ingress Time': '01:00 AM', 'Egress Date': 'Jan 14, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-003-JO-HLS-MGD', 'Sales Executive': 'Cecil Derama', 'Date Created': 'Jan 10, 2024', 'Event Name': 'HERBALIFE SPECTACULAR 2024', 'Venue': 'World Trade Center', 'Event Start Date': 'Jan 13, 2024', 'Event End Date': 'Jan 14, 2024', 'Company Name': 'Quiplist Events Production, Inc.', 'Contact Person': 'Kate Gatchalian', 'Contact No.': '0965-877-1856', 'Email Address': 'prod.quiplist@gmail.com', 'Ingress Date': 'Jan 12, 2024', 'Ingress Time': '01:00 AM', 'Egress Date': 'Jan 14, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-004-JO-CEF-SAN', 'Sales Executive': 'Shaica Naoe', 'Date Created': 'Jan 12, 2024', 'Event Name': 'CANADA EDUCATION FAIR', 'Venue': 'SMX Function Room 3', 'Event Start Date': 'Jan 19, 2024', 'Event End Date': 'Jan 19, 2024', 'Company Name': 'White North Edutech Inc', 'Contact Person': 'Daine Ruth Morales', 'Contact No.': '0915-997-1929', 'Email Address': 'info@canadaeducationfair.ca', 'Ingress Date': 'Jan 19, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 19, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-005-JO-CEF-SAN', 'Sales Executive': 'Shaica Naoe', 'Date Created': 'Jan 12, 2024', 'Event Name': 'Canada EDUCATION FAIR', 'Venue': 'SMX Hall 2', 'Event Start Date': 'Jan 20, 2024', 'Event End Date': 'Jan 20, 2024', 'Company Name': 'White North Edutech Inc', 'Contact Person': 'Daine Ruth Morales', 'Contact No.': '0915-997-1929', 'Email Address': 'info@canadaeducationfair.ca', 'Ingress Date': 'Jan 20, 2024', 'Ingress Time': '02:30 AM', 'Egress Date': 'Jan 20, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-006-JO-ZHR/TTE-MJM', 'Sales Executive': 'Joshua Martinez', 'Date Created': 'Jan 15, 2024', 'Event Name': 'ZURI HOTELS & RESORTS', 'Venue': 'SMX', 'Event Start Date': 'Feb 02, 2024', 'Event End Date': 'Feb 04, 2024', 'Company Name': 'Travel Tour Expo 2024', 'Contact Person': 'Marjorie Gatungay', 'Contact No.': '0917-859-9545', 'Email Address': 'mgatungay@zurihotel@iloilo.com', 'Ingress Date': 'Jan 29, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Feb 04, 2024', 'Egress Time': '07:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-007-JO-PPP-WDC', 'Sales Executive': 'Winlove Campos', 'Date Created': 'Jan 16, 2024', 'Event Name': 'PROPAK PHILIPPINES 2024-OBC', 'Venue': 'World Trade Center', 'Event Start Date': 'Jan 31, 2024', 'Event End Date': 'Feb 02, 2024', 'Company Name': 'Propak Philippines', 'Contact Person': 'Ooi Xiao Hui', 'Contact No.': '0916-335-1598', 'Email Address': 'xiaohui@es-corp.co', 'Ingress Date': 'Jan 29, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Feb 02, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-008-JO-HWC-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 17, 2024', 'Event Name': 'HEALTH AND WELLNESS CONFLEX 2024', 'Venue': 'SMX Hall 3', 'Event Start Date': 'Jan 26, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': 'NAITAS', 'Contact Person': 'Macky B. Soriano', 'Contact No.': '0917-558-1942', 'Email Address': 'mackybsoriano@gmail.com', 'Ingress Date': 'Jan 25, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-009-JO-HWC/DOT-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 17, 2024', 'Event Name': 'HW CONFEX 2024/ DOT PAVILLON', 'Venue': 'SMX Hall 3', 'Event Start Date': 'Jan 26, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': 'NAITAS', 'Contact Person': 'Macky B. Soriano', 'Contact No.': '0917-558-1942', 'Email Address': 'mackybsoriano@gmail.com', 'Ingress Date': 'Jan 25, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-010-JO-WHE-JRB', 'Sales Executive': 'Jesus Bigcas', 'Date Created': 'Jan 17, 2024', 'Event Name': 'WATSONS HEALTH EXPO', 'Venue': 'Megatrade 1-3', 'Event Start Date': 'Feb 01, 2024', 'Event End Date': 'Feb 04, 2024', 'Company Name': 'Eventscape Manila', 'Contact Person': 'Charles Quiazon', 'Contact No.': '0905-462-5124', 'Email Address': 'N/A', 'Ingress Date': 'Jan 30, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Feb 04, 2024', 'Egress Time': '10:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-011-JO-HWC/ITIC-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 17, 2024', 'Event Name': 'HW CONFEX 2024/INNOVA TRADE INGREDIENTS CORP', 'Venue': 'SMX Hall 3', 'Event Start Date': 'Jan 26, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': 'NAITAS', 'Contact Person': 'Diane Marie Pama', 'Contact No.': '0917-558-1942', 'Email Address': 'N/A', 'Ingress Date': 'Jan 25, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-012-JO-HWC/DDPP-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 17, 2024', 'Event Name': 'HW CONFEX 2024/ DTI, DA, PCA PAVILLON', 'Venue': 'SMX Hall 3', 'Event Start Date': 'Jan 26, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': 'NAITAS', 'Contact Person': 'Macky B. Soriano', 'Contact No.': '0917-558-1942', 'Email Address': 'mackybsoriano@gmail.com', 'Ingress Date': 'Jan 25, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-013-JO-HWC/DOH-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 19, 2024', 'Event Name': 'HW CONFEX 2024/ DOH PAVILLON', 'Venue': 'SMX Hall 3', 'Event Start Date': 'Jan 26, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': 'NAITAS', 'Contact Person': 'Macky B. Soriano', 'Contact No.': '0917-558-1942', 'Email Address': 'mackybsoriano@gmail.com', 'Ingress Date': 'Jan 25, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-014-JO-HHB/TTE-SAN', 'Sales Executive': 'Shaica Naoe', 'Date Created': 'Jan 22, 2024', 'Event Name': 'HUE HOTELS BOOTH @ PTAA-TTE', 'Venue': 'SMX', 'Event Start Date': 'Feb 02, 2024', 'Event End Date': 'Feb 04, 2024', 'Company Name': 'Hue Hotels And Resorts ( Luana Lifestyle And Leisure Hotel Inc)', 'Contact Person': 'Ara Sucaldito', 'Contact No.': '0966-192-9209', 'Email Address': 'asucaldito@thehuehotel.com', 'Ingress Date': 'Jan 31, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Feb 04, 2024', 'Egress Time': '10:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-015-JO WDE-WDC', 'Sales Executive': 'Winlove Campos', 'Date Created': 'Jan 22, 2024', 'Event Name': 'WEDDING AND DEBUT 2024 EXPO', 'Venue': 'Okada', 'Event Start Date': 'Jan 27, 2024', 'Event End Date': 'Jan 29, 2024', 'Company Name': 'Wedding And Beyond', 'Contact Person': 'Tet Chua', 'Contact No.': 'N/A', 'Email Address': 'N/A', 'Ingress Date': 'Jan 23, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Jan 29, 2024', 'Egress Time': '12:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-016-JO-CC-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Jan 22, 2024', 'Event Name': 'CHILDRENS CONGRESS 2024', 'Venue': 'CSI Dagupan', 'Event Start Date': 'Feb 05, 2024', 'Event End Date': 'Feb 08, 2024', 'Company Name': 'Rgm Events Management', 'Contact Person': 'Michelle Hilaga', 'Contact No.': '0908-817-9872', 'Email Address': 'N/A', 'Ingress Date': 'Feb 02, 2024', 'Ingress Time': '07:00 AM', 'Egress Date': 'Feb 09, 2024', 'Egress Time': '01:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-017-JO-LG-LJV', 'Sales Executive': 'Lester Visitacion', 'Date Created': 'Jan 24, 2024', 'Event Name': 'LA GERMANIA', 'Venue': 'Commerce Center Alabang', 'Event Start Date': 'Jan 27, 2024', 'Event End Date': 'Jan 28, 2024', 'Company Name': '5 Seconds Advertising', 'Contact Person': 'Bocs Lina', 'Contact No.': '0917-849-0782', 'Email Address': 'N/A', 'Ingress Date': 'Jan 27, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Jan 28, 2024', 'Egress Time': '10:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-018-JO-SWC-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Jan 26, 2024', 'Event Name': 'SURF WAIS CONVENTION 2024', 'Venue': 'Megatrade Hall 1, 2', 'Event Start Date': 'Feb 10, 2024', 'Event End Date': 'Feb 11, 2024', 'Company Name': 'Summit Media', 'Contact Person': 'Aileen Camansag', 'Contact No.': '0966-204-6024', 'Email Address': 'aileen.camansag@summitmedia.com.ph', 'Ingress Date': 'Feb 09, 2024', 'Ingress Time': '10:00 PM', 'Egress Date': 'Feb 11, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-019-JO-NTC-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Jan 29, 2024', 'Event Name': 'NATIONAL TEXTILE CONVENTION 2024', 'Venue': 'PICC', 'Event Start Date': 'Jan 30, 2024', 'Event End Date': 'Jan 31, 2024', 'Company Name': 'Philippines Textile Research Institute', 'Contact Person': 'Angelito T. Uldo', 'Contact No.': '0916-264-8314', 'Email Address': 'N/A', 'Ingress Date': 'Jan 30, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Jan 31, 2024', 'Egress Time': '07:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-020-JO-PAC-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Jan 29, 2024', 'Event Name': '31ST PIDSIP ANNUAL CONVENTION', 'Venue': 'Crown Plaza Galleria', 'Event Start Date': 'Feb 21, 2024', 'Event End Date': 'Feb 22, 2024', 'Company Name': 'PIDSIP', 'Contact Person': 'Mary Manese', 'Contact No.': '0915-087-9966', 'Email Address': 'N/A', 'Ingress Date': 'Feb 20, 2024', 'Ingress Time': '03:00 PM', 'Egress Date': 'Feb 22, 2024', 'Egress Time': '10:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-021-JO-NHSM-MGD', 'Sales Executive': 'Cecil Derama', 'Date Created': 'Jan 30, 2024', 'Event Name': 'NATIONAL HEALTH SECTOR MEETING', 'Venue': 'Sofitel Hotel', 'Event Start Date': 'Jan 31, 2024', 'Event End Date': 'Jan 31, 2024', 'Company Name': 'Sofitel Harbor Sector Meeting', 'Contact Person': 'Mr.Sherrald Osarman', 'Contact No.': '0945-829-0188', 'Email Address': 'N/A', 'Ingress Date': 'Jan 30, 2024', 'Ingress Time': '10:00 PM', 'Egress Date': 'Jan 31, 2024', 'Egress Time': '04:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-022-JO-UAPC-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Feb 01, 2024', 'Event Name': 'UAP CONEX 2024', 'Venue': 'SMX', 'Event Start Date': 'Apr 18, 2024', 'Event End Date': 'Apr 20, 2024', 'Company Name': 'United Architects Of The Philippines', 'Contact Person': 'Evelyn Franco', 'Contact No.': '(8)888-9266', 'Email Address': 'N/A', 'Ingress Date': 'Apr 15, 2024', 'Ingress Time': '06:00 AM', 'Egress Date': 'Apr 20, 2024', 'Egress Time': '07:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-023-JO-NTC/STP-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Feb 02, 2024', 'Event Name': 'NATIONAL TEXTILE CONVENTION 2024', 'Venue': 'Senate of the Philippines', 'Event Start Date': 'Feb 05, 2024', 'Event End Date': 'Feb 10, 2024', 'Company Name': 'Philippines Textile Research Institute', 'Contact Person': 'Angelito T. Uldo', 'Contact No.': '0916-264-8314', 'Email Address': 'N/A', 'Ingress Date': 'Feb 01, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Feb 10, 2024', 'Egress Time': '07:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-024-JO-TWL/EBEI-LJV', 'Sales Executive': 'Lester Visitacion', 'Date Created': 'Feb 02, 2024', 'Event Name': 'THE WEDDING LIBRARY', 'Venue': 'World Trade Center', 'Event Start Date': 'Feb 09, 2024', 'Event End Date': 'Feb 11, 2024', 'Company Name': 'Engagement By Elle Inc.', 'Contact Person': 'Larizze Bonifacio', 'Contact No.': '0966-210-0620', 'Email Address': 'N/A', 'Ingress Date': 'Feb 08, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Feb 11, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-025-JO-GPW-MGD', 'Sales Executive': 'Cecil Derama', 'Date Created': 'Feb 02, 2024', 'Event Name': 'GRAND PHILS @ WORLDBEX 2024', 'Venue': 'World Trade Center', 'Event Start Date': 'Mar 14, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'Grand Philippines', 'Contact Person': 'Jeffrey Tan', 'Contact No.': '0933-247-6955', 'Email Address': 'grandphilippines@gmail.com', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '10:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-026-JO-TWL-WDC', 'Sales Executive': 'Winlove Campos', 'Date Created': 'Feb 05, 2024', 'Event Name': 'WEDDING AND DEBUT 2024 EXPO', 'Venue': 'WTC HALL A-C', 'Event Start Date': 'Feb 09, 2024', 'Event End Date': 'Feb 11, 2024', 'Company Name': 'The Wedding Library', 'Contact Person': 'Winnie Natividad', 'Contact No.': 'N/A', 'Email Address': 'N/A', 'Ingress Date': 'Feb 08, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Feb 11, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-027-JO-DHRD-LJV', 'Sales Executive': 'Lester Visitacion', 'Date Created': 'Feb 05, 2024', 'Event Name': 'THE WEDDING LIBRARY BOOTH A006', 'Venue': 'World Trade Center', 'Event Start Date': 'Feb 09, 2024', 'Event End Date': 'Feb 11, 2024', 'Company Name': 'Dusit Hotels & Resort In Davao', 'Contact Person': 'Jennifer Tuballes', 'Contact No.': '0995-177-6068', 'Email Address': 'N/A', 'Ingress Date': 'Feb 08, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Feb 11, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-028-JO-CPFE-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Feb 16, 2024', 'Event Name': 'CANADA PHILS. FAIR & EXHIBITS', 'Venue': 'TRINOMA MALL', 'Event Start Date': 'Feb 16, 2024', 'Event End Date': 'Feb 16, 2024', 'Company Name': 'Rgm Events Management', 'Contact Person': 'Michelle Hilaga', 'Contact No.': '0908-817-9872', 'Email Address': 'michellergmevents@gmail.com', 'Ingress Date': 'Feb 15, 2024', 'Ingress Time': '09:00 PM', 'Egress Date': 'Feb 16, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-029-JO-PPHE-JRB', 'Sales Executive': 'Jesus Bigcas', 'Date Created': 'Feb 13, 2024', 'Event Name': 'PHILIPPINES PHARMA AND HEALTH EXPO', 'Venue': 'SMX CONVENTION CENTER', 'Event Start Date': 'Feb 13, 2024', 'Event End Date': 'Feb 16, 2024', 'Company Name': 'Uniglobal', 'Contact Person': 'Praveen', 'Contact No.': '91 9560037594', 'Email Address': 'N/A', 'Ingress Date': 'Feb 13, 2024', 'Ingress Time': '03:00 PM', 'Egress Date': 'Feb 16, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-030-JO-WB-WDC', 'Sales Executive': 'Winlove Campos', 'Date Created': 'Feb 13, 2024', 'Event Name': 'Worldbex 2024', 'Venue': 'SMX CONVENTION CENTER HALL 1-4', 'Event Start Date': 'Mar 14, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'WSI', 'Contact Person': 'Jill Ang', 'Contact No.': 'N/A', 'Email Address': 'jill.worldbex@gmail.com', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-031-JO-NTC/MCG-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Feb 13, 2024', 'Event Name': 'NATIONAL TEXTILE CONVENTION 2024/ MALACANANG', 'Venue': 'SENATE OF THE PHILIPPINES', 'Event Start Date': 'Dec 30, 1899', 'Event End Date': 'Dec 30, 1899', 'Company Name': 'DOST', 'Contact Person': 'Angelito T. Uldo', 'Contact No.': '0916-264-8314', 'Email Address': 'N/A', 'Ingress Date': 'Dec 30, 1899', 'Ingress Time': '08:00 AM', 'Egress Date': 'Feb 29, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-032-JO/PEC-MJM', 'Sales Executive': 'Joshua Martinez', 'Date Created': 'Feb 15, 2024', 'Event Name': 'PRIMA @ WORLDBEX 2024', 'Venue': 'SMX', 'Event Start Date': 'Mar 14, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'Prima Enterprise', 'Contact Person': 'Benjamin Gokingyok', 'Contact No.': '0962-217-8864', 'Email Address': 'c.elon@primal.com.ph, mktg-1@prima.com.ph', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-033-JO-FKE-JRB', 'Sales Executive': 'Jesus Bigcas', 'Date Created': 'Feb 15, 2024', 'Event Name': 'FANTOPIA', 'Venue': 'MEGATRADE', 'Event Start Date': 'Feb 18, 2024', 'Event End Date': 'Feb 18, 2024', 'Company Name': 'Makeitive', 'Contact Person': 'Arnold Cabales', 'Contact No.': '0998-990-0069', 'Email Address': 'N/A', 'Ingress Date': 'Feb 18, 2024', 'Ingress Time': '04:00 AM', 'Egress Date': 'Feb 18, 2024', 'Egress Time': '09:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-034-JO-PCR-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Feb 15, 2024', 'Event Name': 'PHIL. COLLEGE OF RADIOLOGY', 'Venue': 'SMX COVENTION CENTER', 'Event Start Date': 'Feb 22, 2024', 'Event End Date': 'Feb 24, 2024', 'Company Name': 'Westlines Design Technologies Corp.', 'Contact Person': 'Ben Mangiliman', 'Contact No.': '0917-813-3740', 'Email Address': 'arjcr@westlines.design', 'Ingress Date': 'Feb 21, 2024', 'Ingress Time': '03:00 AM', 'Egress Date': 'Feb 24, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-035-JO-IRBF-WDC', 'Sales Executive': '', 'Date Created': 'Dec 30, 1899', 'Event Name': 'INSIDE RACING BIKE FEST 2024', 'Venue': 'WORLD TRADE CENTER HALL', 'Event Start Date': 'Dec 30, 1899', 'Event End Date': 'Dec 30, 1899', 'Company Name': 'Inside Racing', 'Contact Person': 'Jennifer Morente', 'Contact No.': '', 'Email Address': '', 'Ingress Date': 'Dec 30, 1899', 'Ingress Time': '12:00 AM', 'Egress Date': 'Dec 30, 1899', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-036-JO-WCS-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Feb 19, 2024', 'Event Name': 'WORLD CHAMPIONSHIP SKATEBOARDING', 'Venue': 'FORA MALL, TAGAYTAY CITY', 'Event Start Date': 'Feb 21, 2024', 'Event End Date': 'Feb 25, 2024', 'Company Name': 'Bluefish Asia Events & Media', 'Contact Person': 'Kathleen Cervantes', 'Contact No.': '0917-521-3899', 'Email Address': 'katcervantes@bluefish-asia.com', 'Ingress Date': 'Feb 21, 2024', 'Ingress Time': '03:00 AM', 'Egress Date': 'Feb 25, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-037-JO-PCP-LHE', 'Sales Executive': 'Loremer Elbano', 'Date Created': 'Feb 20, 2024', 'Event Name': 'PHIDEX', 'Venue': 'World Trade Center', 'Event Start Date': 'Feb 23, 2024', 'Event End Date': 'Feb 25, 2024', 'Company Name': 'Cityneon Philippines Inc', 'Contact Person': 'Patrick Tirado', 'Contact No.': '0920-986-0408', 'Email Address': 'N/A', 'Ingress Date': 'Feb 22, 2024', 'Ingress Time': '06:00 AM', 'Egress Date': 'Feb 25, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-038-JO-MWSI-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Dec 30, 1899', 'Event Name': 'MIAS 2024', 'Venue': 'WORLD TRADE CENTER', 'Event Start Date': 'Dec 30, 1899', 'Event End Date': 'Dec 30, 1899', 'Company Name': 'WSI', 'Contact Person': 'Jill Ang', 'Contact No.': 'N/A', 'Email Address': 'N/A', 'Ingress Date': 'Dec 30, 1899', 'Ingress Time': '12:00 AM', 'Egress Date': 'Dec 30, 1899', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-039-JO-USAF-KHG', 'Sales Executive': 'Keren Huarde', 'Date Created': 'Feb 21, 2024', 'Event Name': 'UP STUDY ABROAD FAIR 2024', 'Venue': 'University of the Philippines Diliman', 'Event Start Date': 'Feb 27, 2024', 'Event End Date': 'Mar 02, 2024', 'Company Name': 'University Of The Philippines, Office Of International Linkage, Diliman', 'Contact Person': 'Ariane Francisco', 'Contact No.': '0967-698-0208', 'Email Address': 'apfrancisco4@up.edu.ph', 'Ingress Date': 'Feb 26, 2024', 'Ingress Time': '01:00 PM', 'Egress Date': 'Mar 02, 2024', 'Egress Time': '05:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-040-JO-GPWB-MGD', 'Sales Executive': 'Cecil Derama', 'Date Created': 'Feb 28, 2024', 'Event Name': 'GRAND PHILIPPINES @ WORLDBEX 2024', 'Venue': 'WORLD TRADE CENTER, MANILA', 'Event Start Date': 'Mar 11, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'Grand Philippines', 'Contact Person': 'Jeffrey Tan', 'Contact No.': '0933-247-6955', 'Email Address': 'grandphilippines@gmail.com', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '10:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-041-JO-FFCCCII-KHG', 'Sales Executive': 'Keren Huarde', 'Date Created': 'Feb 28, 2024', 'Event Name': 'FFCCCII', 'Venue': 'FFCCCII OFFICE, FEDERATION CENTER, MLLE. DE BINONDO, MANILA, 1006 METRO MANILA', 'Event Start Date': 'Mar 06, 2024', 'Event End Date': 'Mar 11, 2024', 'Company Name': 'WSI/Ffcccii', 'Contact Person': 'Jill Ang / Sir Gino', 'Contact No.': 'N/A', 'Email Address': 'jill.worldbex@gmail.com', 'Ingress Date': 'Mar 06, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 11, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-042-JO-PCAC-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Feb 29, 2024', 'Event Name': '43RD PCCP CHEST ANNUAL CONVENTION', 'Venue': 'PALAWAN ROOM, EDSA SHANGRILA HOTEL, MANDALUYONG CITY', 'Event Start Date': 'Mar 05, 2024', 'Event End Date': 'Mar 08, 2024', 'Company Name': 'FBC Tycoon', 'Contact Person': 'Florentino Calzado', 'Contact No.': '0919-002-5687', 'Email Address': 'N/A', 'Ingress Date': 'Mar 05, 2024', 'Ingress Time': '01:00 AM', 'Egress Date': 'Mar 08, 2024', 'Egress Time': '08:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-043-JO-FPP-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Mar 04, 2024', 'Event Name': '1ST PHILPOWER EXPO', 'Venue': 'SMX AURA, HALL 1', 'Event Start Date': 'Mar 08, 2024', 'Event End Date': 'Mar 09, 2024', 'Company Name': 'PSME Foundation', 'Contact Person': 'Shiela Irlandez', 'Contact No.': '0917-550-0002', 'Email Address': 'N/A', 'Ingress Date': 'Mar 07, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 09, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-044-JO-MPTI-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Mar 06, 2024', 'Event Name': 'MIAS 2024.', 'Venue': 'EAST WING TENT A, WORLD TRADE CENTER', 'Event Start Date': 'Apr 04, 2024', 'Event End Date': 'Apr 07, 2024', 'Company Name': 'Profilm- Top Innovations Inc', 'Contact Person': 'Fhoebie De Vera', 'Contact No.': '0917-658-0952', 'Email Address': 'N/A', 'Ingress Date': 'Apr 01, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Apr 07, 2024', 'Egress Time': '09:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-045-JO-WBP-WDC', 'Sales Executive': 'Winlove Campos', 'Date Created': 'Mar 06, 2024', 'Event Name': 'WORLDBEX 2024 @ pavillon', 'Venue': 'SMX & WTC TENT A&B', 'Event Start Date': 'Mar 14, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'WSI', 'Contact Person': 'Jill Ang', 'Contact No.': 'N/A', 'Email Address': 'jill.worldbex@gmail.com', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-046-JO-MRTI-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Mar 06, 2024', 'Event Name': 'MIAS 2024', 'Venue': 'EAST WING TENT A, WORLD TRADE CENTER', 'Event Start Date': 'Apr 04, 2024', 'Event End Date': 'Apr 07, 2024', 'Company Name': 'Rage - Top Innovations Inc.', 'Contact Person': 'Fhoebie De Vera', 'Contact No.': '0917-658-0952', 'Email Address': 'N/A', 'Ingress Date': 'Apr 01, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Apr 07, 2024', 'Egress Time': '09:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-047-IR/GOP-LJV', 'Sales Executive': 'Lester Visitacion', 'Date Created': 'Mar 06, 2024', 'Event Name': 'INSIDE RACING BIKE FEST 2024 BOOTH NUMBER B6', 'Venue': 'WORLD TRADE CENTER', 'Event Start Date': 'Mar 22, 2024', 'Event End Date': 'Mar 24, 2024', 'Company Name': 'Gulf Oil Philippines', 'Contact Person': 'Sheila Anne B. Padon', 'Contact No.': '0995-091-0449', 'Email Address': 'N/A', 'Ingress Date': 'Mar 20, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Mar 24, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-048-JO-MPEC-MJM', 'Sales Executive': 'Joshua Martinez', 'Date Created': 'Mar 06, 2024', 'Event Name': 'MIAS 2024', 'Venue': 'SMX CONVENTION CENTER', 'Event Start Date': 'Apr 04, 2024', 'Event End Date': 'Apr 07, 2024', 'Company Name': 'Primal Eneterprises Corp.', 'Contact Person': 'Katerina', 'Contact No.': '0962-217-8864', 'Email Address': 'c.elon@primal.com.ph, mktg-1@primal.com.ph', 'Ingress Date': 'Apr 01, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Apr 07, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-049-JO-NWM-JRB', 'Sales Executive': 'Jesus Bigcas', 'Date Created': 'Mar 06, 2024', 'Event Name': 'NATIONAL WOMENS MONTH', 'Venue': 'DEPARTMENT OF MIGRANT WORKERS', 'Event Start Date': 'Mar 08, 2024', 'Event End Date': 'Mar 22, 2024', 'Company Name': 'Department Of Migrant Workers', 'Contact Person': 'Neil Burdeos', 'Contact No.': '0917-806-3288', 'Email Address': 'N/A', 'Ingress Date': 'Mar 07, 2024', 'Ingress Time': '03:00 PM', 'Egress Date': 'Mar 22, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-050-JO-MZTI-EDL', 'Sales Executive': 'Elvis Lorenzo', 'Date Created': 'Mar 06, 2024', 'Event Name': 'MIAS 2024', 'Venue': 'EAST WING TENT A, WORLD TRADE CENTER', 'Event Start Date': 'Apr 04, 2024', 'Event End Date': 'Apr 07, 2024', 'Company Name': 'Zivent-Top Innovations Inc', 'Contact Person': 'Fhoebie De Vera', 'Contact No.': '0917-658-0952', 'Email Address': 'N/A', 'Ingress Date': 'Apr 01, 2024', 'Ingress Time': '05:00 AM', 'Egress Date': 'Apr 07, 2024', 'Egress Time': '09:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-051-JO-IR/UPP-LJV', 'Sales Executive': 'Lester Visitacion', 'Date Created': 'Mar 07, 2024', 'Event Name': 'INSIDE RACING BIKE FEST BOOTH A14', 'Venue': 'WORLD TRADE CENTER', 'Event Start Date': 'Mar 22, 2024', 'Event End Date': 'Mar 24, 2024', 'Company Name': 'Unioil Petroluem Philippines, Inc', 'Contact Person': 'Edel Myrrh Faith Cipriani', 'Contact No.': '0995-091-0449', 'Email Address': 'N/A', 'Ingress Date': 'Mar 20, 2024', 'Ingress Time': '12:00 AM', 'Egress Date': 'Mar 24, 2024', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-052-JO-WB/EAD', 'Sales Executive': 'Prescious Nim', 'Date Created': 'Mar 07, 2024', 'Event Name': 'Worldbex 2024', 'Venue': 'SMX GROUNDFLOOR', 'Event Start Date': 'Mar 14, 2024', 'Event End Date': 'Mar 17, 2024', 'Company Name': 'Edwin D. Uy Architecture Interior & Design Office', 'Contact Person': 'Michael John A. Laviste', 'Contact No.': '0917-596-0280', 'Email Address': 'mj.laviste@edwinuy.ph', 'Ingress Date': 'Mar 11, 2024', 'Ingress Time': '08:00 AM', 'Egress Date': 'Mar 17, 2024', 'Egress Time': '06:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-053-JO-DPKE-APG', 'Sales Executive': 'Alma Guilalas', 'Date Created': 'Mar 07, 2024', 'Event Name': 'DOST-PTRI KATHABI EXHIBITION (RE; SET-UP)', 'Venue': 'HOUSE OF PRESIDENT MALACANANG', 'Event Start Date': 'Dec 30, 1899', 'Event End Date': 'Dec 30, 1899', 'Company Name': 'Philippine Textile Research Institute', 'Contact Person': 'Angelito T. Uldo', 'Contact No.': '0916-264-8314', 'Email Address': 'N/A', 'Ingress Date': 'Dec 30, 1899', 'Ingress Time': '12:00 AM', 'Egress Date': 'Dec 30, 1899', 'Egress Time': '12:00 AM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''},
    {'JO No.': '24-054-JO-KATF-DJD', 'Sales Executive': 'Denis Domingo', 'Date Created': 'Mar 08, 2024', 'Event Name': '', 'Venue': '', 'Event Start Date': 'Mar 18, 2024', 'Event End Date': 'Mar 20, 2024', 'Company Name': 'City Trade And Industry Dept. Calapan', 'Contact Person': 'Joanne Leynes', 'Contact No.': '0943-329-8896', 'Email Address': 'joanne.leynes@yahoo.com', 'Ingress Date': 'Mar 17, 2024', 'Ingress Time': '06:00 AM', 'Egress Date': 'Mar 20, 2024', 'Egress Time': '09:00 PM', 'BOM Preparer': '', 'BOM Reviewer': '', 'BOM Approver': ''}

] 

table_columns = [
    {'name': 'JO No.', 'id' : 'JO No.'},
    {'name': 'Sales Executive', 'id' : 'Sales Executive'},
    {'name': 'Date Created', 'id' : 'Date Created'},
    {'name': 'Event Name', 'id' : 'Event Name'},
    {'name': 'Venue', 'id' : 'Venue'},
    {'name': 'Event Start Date', 'id' : 'Event Start Date'},
    {'name': 'Event End Date', 'id' : 'Event End Date'},
    {'name': 'Company Name', 'id' : 'Company Name'},
    {'name': 'Contact Person', 'id' : 'Contact Person'},
    {'name': 'Contact No.', 'id' : 'Contact No.'},
    {'name': 'Email Address', 'id' : 'Email Address'},
    {'name': 'Ingress Date', 'id' : 'Ingress Date'},
    {'name': 'Ingress Time', 'id' : 'Ingress Time'},
    {'name': 'Egress Date', 'id' : 'Egress Date'},
    {'name': 'Egress Time', 'id' : 'Egress Time'},
    {'name': 'BOM Preparer', 'id' : 'BOM Preparer'},
    {'name': 'BOM Reviewer', 'id' : 'BOM Reviewer'},
    {'name': 'BOM Approver', 'id' : 'BOM Approver'}

]


def render() -> dbc.Col:
    return dbc.Col([
        dbc.Row([
            dbc.Col(html.H3("JO-BOM List:", style={'font-family': 'Tahoma', 'font-size': '25px',
                'font-weight': 'bold'}), width=2, className="d-flex align-items-center"),
        ]),

        dbc.Row([
            dbc.Col(dash_table.DataTable(
                id='jobom-table',
                columns=table_columns,
                data=table_data,
                editable=False,
                page_size=10,
                style_table=TABLE_STYLE,
                style_cell=TABLE_CELL_STYLE,
                style_header=TABLE_HEADER_STYLE,
            )),
        ]),

    ], style={'margin-top': '20px', 'width': '800px', 'height': '100%'})

# @callback(Output('jobom-table', 'data'), Input('url', 'pathname'))
# def load_employees(pathname):
#     if pathname == '/':
#         employees: list[Employee] = get_employees()
#         table_data = [
#             {
#                 'ID': employee.employee_id,
#                 'Employee Name': f'{employee.first_name} {employee.last_name}',
#                 'Department': employee.department_name,
#                 'Position Title': employee.employee_position_title,
#                 'Contact No.': employee.contact_no,
#                 'Email Address': employee.email_address
#             }
#             for employee in employees
#         ]
#     else:
#         table_data = []

#     return table_data
